package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.CustomerContact;
import com.wuseguang.report.db.pojo.CustomerContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int countByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int deleteByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int insert(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int insertSelective(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    List<CustomerContact> selectByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    CustomerContact selectByPrimaryKey(@Param("columns") String columns, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") CustomerContact record, @Param("example") CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int updateByExample(@Param("record") CustomerContact record, @Param("example") CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int updateByPrimaryKeySelective(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    int updateByPrimaryKey(CustomerContact record);
}