package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.Customer;
import com.wuseguang.report.db.pojo.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	Customer selectByPrimaryKey(@Param("columns") String columns,
			@Param("id") Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Customer record,
			@Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByExample(@Param("record") Customer record,
			@Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByPrimaryKeySelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByPrimaryKey(Customer record);
}