package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.Department;
import com.wuseguang.report.db.pojo.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int countByExample(DepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int deleteByExample(DepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int insertSelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	List<Department> selectByExample(DepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	Department selectByPrimaryKey(@Param("columns") String columns,
			@Param("id") Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Department record,
			@Param("example") DepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByExample(@Param("record") Department record,
			@Param("example") DepartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByPrimaryKeySelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	int updateByPrimaryKey(Department record);
}