package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.EnterpriseChina;
import com.wuseguang.report.db.pojo.EnterpriseChinaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnterpriseChinaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int countByExample(EnterpriseChinaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int deleteByExample(EnterpriseChinaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int insert(EnterpriseChina record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int insertSelective(EnterpriseChina record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	List<EnterpriseChina> selectByExample(EnterpriseChinaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	EnterpriseChina selectByPrimaryKey(@Param("columns") String columns,
			@Param("id") Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int updateByExampleSelective(@Param("record") EnterpriseChina record,
			@Param("example") EnterpriseChinaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int updateByExample(@Param("record") EnterpriseChina record,
			@Param("example") EnterpriseChinaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int updateByPrimaryKeySelective(EnterpriseChina record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_china
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	int updateByPrimaryKey(EnterpriseChina record);
}