package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.EntShareholderList;
import com.wuseguang.report.db.pojo.EntShareholderListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntShareholderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int countByExample(EntShareholderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int deleteByExample(EntShareholderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int insert(EntShareholderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int insertSelective(EntShareholderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    List<EntShareholderList> selectByExample(EntShareholderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    EntShareholderList selectByPrimaryKey(@Param("columns") String columns, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") EntShareholderList record, @Param("example") EntShareholderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByExample(@Param("record") EntShareholderList record, @Param("example") EntShareholderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByPrimaryKeySelective(EntShareholderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder_list
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByPrimaryKey(EntShareholderList record);
}