package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.EntShareholder;
import com.wuseguang.report.db.pojo.EntShareholderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntShareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int countByExample(EntShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int deleteByExample(EntShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int insert(EntShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int insertSelective(EntShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    List<EntShareholder> selectByExample(EntShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    EntShareholder selectByPrimaryKey(@Param("columns") String columns, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") EntShareholder record, @Param("example") EntShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByExample(@Param("record") EntShareholder record, @Param("example") EntShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByPrimaryKeySelective(EntShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    int updateByPrimaryKey(EntShareholder record);
}