package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.Person;
import com.wuseguang.report.db.pojo.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int countByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int deleteByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	List<Person> selectByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	Person selectByPrimaryKey(@Param("columns") String columns,
			@Param("id") Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Person record,
			@Param("example") PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int updateByExample(@Param("record") Person record,
			@Param("example") PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int updateByPrimaryKeySelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	int updateByPrimaryKey(Person record);
}