package com.wuseguang.report.db.dao;

import com.wuseguang.report.db.pojo.UserBase;
import com.wuseguang.report.db.pojo.UserBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int countByExample(UserBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int deleteByExample(UserBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int insert(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int insertSelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	List<UserBase> selectByExample(UserBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	UserBase selectByPrimaryKey(@Param("columns") String columns,
			@Param("id") Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int updateByExampleSelective(@Param("record") UserBase record,
			@Param("example") UserBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int updateByExample(@Param("record") UserBase record,
			@Param("example") UserBaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int updateByPrimaryKeySelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	int updateByPrimaryKey(UserBase record);
}