package com.wuseguang.report.db.pojo;

public class CustomerContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_name
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_sex
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_role
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_position
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_telphone
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_mobile
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_email
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contact.customer_contact_remark
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    private String customerContactRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.id
     *
     * @return the value of customer_contact.id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.id
     *
     * @param id the value for customer_contact.id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_name
     *
     * @return the value of customer_contact.customer_contact_name
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactName() {
        return customerContactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_name
     *
     * @param customerContactName the value for customer_contact.customer_contact_name
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactName(String customerContactName) {
        this.customerContactName = customerContactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_sex
     *
     * @return the value of customer_contact.customer_contact_sex
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactSex() {
        return customerContactSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_sex
     *
     * @param customerContactSex the value for customer_contact.customer_contact_sex
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactSex(String customerContactSex) {
        this.customerContactSex = customerContactSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_role
     *
     * @return the value of customer_contact.customer_contact_role
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactRole() {
        return customerContactRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_role
     *
     * @param customerContactRole the value for customer_contact.customer_contact_role
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactRole(String customerContactRole) {
        this.customerContactRole = customerContactRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_position
     *
     * @return the value of customer_contact.customer_contact_position
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactPosition() {
        return customerContactPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_position
     *
     * @param customerContactPosition the value for customer_contact.customer_contact_position
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactPosition(String customerContactPosition) {
        this.customerContactPosition = customerContactPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_telphone
     *
     * @return the value of customer_contact.customer_contact_telphone
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactTelphone() {
        return customerContactTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_telphone
     *
     * @param customerContactTelphone the value for customer_contact.customer_contact_telphone
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactTelphone(String customerContactTelphone) {
        this.customerContactTelphone = customerContactTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_mobile
     *
     * @return the value of customer_contact.customer_contact_mobile
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactMobile() {
        return customerContactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_mobile
     *
     * @param customerContactMobile the value for customer_contact.customer_contact_mobile
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactMobile(String customerContactMobile) {
        this.customerContactMobile = customerContactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_email
     *
     * @return the value of customer_contact.customer_contact_email
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactEmail() {
        return customerContactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_email
     *
     * @param customerContactEmail the value for customer_contact.customer_contact_email
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactEmail(String customerContactEmail) {
        this.customerContactEmail = customerContactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_id
     *
     * @return the value of customer_contact.customer_id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_id
     *
     * @param customerId the value for customer_contact.customer_id
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contact.customer_contact_remark
     *
     * @return the value of customer_contact.customer_contact_remark
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public String getCustomerContactRemark() {
        return customerContactRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contact.customer_contact_remark
     *
     * @param customerContactRemark the value for customer_contact.customer_contact_remark
     *
     * @mbggenerated Thu Dec 26 19:36:52 CST 2013
     */
    public void setCustomerContactRemark(String customerContactRemark) {
        this.customerContactRemark = customerContactRemark;
    }
}