package com.wuseguang.report.db.pojo;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.id
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_name
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_type
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_address
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_zipcode
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_telphone
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerTelphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_shortname
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerShortname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_email
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_fax
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_web
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerWeb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_remark
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private String customerRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_userid
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	private Integer customerUserid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.id
	 * @return  the value of customer.id
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.id
	 * @param id  the value for customer.id
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_name
	 * @return  the value of customer.customer_name
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_name
	 * @param customerName  the value for customer.customer_name
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_type
	 * @return  the value of customer.customer_type
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerType() {
		return customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_type
	 * @param customerType  the value for customer.customer_type
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_address
	 * @return  the value of customer.customer_address
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerAddress() {
		return customerAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_address
	 * @param customerAddress  the value for customer.customer_address
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_zipcode
	 * @return  the value of customer.customer_zipcode
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerZipcode() {
		return customerZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_zipcode
	 * @param customerZipcode  the value for customer.customer_zipcode
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerZipcode(String customerZipcode) {
		this.customerZipcode = customerZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_telphone
	 * @return  the value of customer.customer_telphone
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerTelphone() {
		return customerTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_telphone
	 * @param customerTelphone  the value for customer.customer_telphone
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerTelphone(String customerTelphone) {
		this.customerTelphone = customerTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_shortname
	 * @return  the value of customer.customer_shortname
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerShortname() {
		return customerShortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_shortname
	 * @param customerShortname  the value for customer.customer_shortname
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerShortname(String customerShortname) {
		this.customerShortname = customerShortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_email
	 * @return  the value of customer.customer_email
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerEmail() {
		return customerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_email
	 * @param customerEmail  the value for customer.customer_email
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_fax
	 * @return  the value of customer.customer_fax
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerFax() {
		return customerFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_fax
	 * @param customerFax  the value for customer.customer_fax
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerFax(String customerFax) {
		this.customerFax = customerFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_web
	 * @return  the value of customer.customer_web
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerWeb() {
		return customerWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_web
	 * @param customerWeb  the value for customer.customer_web
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerWeb(String customerWeb) {
		this.customerWeb = customerWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_remark
	 * @return  the value of customer.customer_remark
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getCustomerRemark() {
		return customerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_remark
	 * @param customerRemark  the value for customer.customer_remark
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerRemark(String customerRemark) {
		this.customerRemark = customerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.customer_userid
	 * @return  the value of customer.customer_userid
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public Integer getCustomerUserid() {
		return customerUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.customer_userid
	 * @param customerUserid  the value for customer.customer_userid
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setCustomerUserid(Integer customerUserid) {
		this.customerUserid = customerUserid;
	}
}