package com.wuseguang.report.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepartmentExample extends BaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public DepartmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null)
				return;
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null)
				return;
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null)
				return;
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDepartTimeIsNull() {
			addCriterion("depart_time is null");
			return (Criteria) this;
		}

		public Criteria andDepartTimeIsNotNull() {
			addCriterion("depart_time is not null");
			return (Criteria) this;
		}

		public Criteria andDepartTimeEqualTo(Date value) {
			addCriterion("depart_time =", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeNotEqualTo(Date value) {
			addCriterion("depart_time <>", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeGreaterThan(Date value) {
			addCriterion("depart_time >", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("depart_time >=", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeLessThan(Date value) {
			addCriterion("depart_time <", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeLessThanOrEqualTo(Date value) {
			addCriterion("depart_time <=", value, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeIn(List<Date> values) {
			addCriterion("depart_time in", values, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeNotIn(List<Date> values) {
			addCriterion("depart_time not in", values, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeBetween(Date value1, Date value2) {
			addCriterion("depart_time between", value1, value2, "departTime");
			return (Criteria) this;
		}

		public Criteria andDepartTimeNotBetween(Date value1, Date value2) {
			addCriterion("depart_time not between", value1, value2,
					"departTime");
			return (Criteria) this;
		}

		public Criteria andDepartNameIsNull() {
			addCriterion("depart_name is null");
			return (Criteria) this;
		}

		public Criteria andDepartNameIsNotNull() {
			addCriterion("depart_name is not null");
			return (Criteria) this;
		}

		public Criteria andDepartNameEqualTo(String value) {
			addCriterion("depart_name =", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameNotEqualTo(String value) {
			addCriterion("depart_name <>", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameGreaterThan(String value) {
			addCriterion("depart_name >", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameGreaterThanOrEqualTo(String value) {
			addCriterion("depart_name >=", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameLessThan(String value) {
			addCriterion("depart_name <", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameLessThanOrEqualTo(String value) {
			addCriterion("depart_name <=", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameLike(String value) {
			addCriterion("depart_name like", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameNotLike(String value) {
			addCriterion("depart_name not like", value, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameIn(List<String> values) {
			addCriterion("depart_name in", values, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameNotIn(List<String> values) {
			addCriterion("depart_name not in", values, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameBetween(String value1, String value2) {
			addCriterion("depart_name between", value1, value2, "departName");
			return (Criteria) this;
		}

		public Criteria andDepartNameNotBetween(String value1, String value2) {
			addCriterion("depart_name not between", value1, value2,
					"departName");
			return (Criteria) this;
		}

		public Criteria andDepartCodeIsNull() {
			addCriterion("depart_code is null");
			return (Criteria) this;
		}

		public Criteria andDepartCodeIsNotNull() {
			addCriterion("depart_code is not null");
			return (Criteria) this;
		}

		public Criteria andDepartCodeEqualTo(String value) {
			addCriterion("depart_code =", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeNotEqualTo(String value) {
			addCriterion("depart_code <>", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeGreaterThan(String value) {
			addCriterion("depart_code >", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeGreaterThanOrEqualTo(String value) {
			addCriterion("depart_code >=", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeLessThan(String value) {
			addCriterion("depart_code <", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeLessThanOrEqualTo(String value) {
			addCriterion("depart_code <=", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeLike(String value) {
			addCriterion("depart_code like", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeNotLike(String value) {
			addCriterion("depart_code not like", value, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeIn(List<String> values) {
			addCriterion("depart_code in", values, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeNotIn(List<String> values) {
			addCriterion("depart_code not in", values, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeBetween(String value1, String value2) {
			addCriterion("depart_code between", value1, value2, "departCode");
			return (Criteria) this;
		}

		public Criteria andDepartCodeNotBetween(String value1, String value2) {
			addCriterion("depart_code not between", value1, value2,
					"departCode");
			return (Criteria) this;
		}

		public Criteria andDepartContactIsNull() {
			addCriterion("depart_contact is null");
			return (Criteria) this;
		}

		public Criteria andDepartContactIsNotNull() {
			addCriterion("depart_contact is not null");
			return (Criteria) this;
		}

		public Criteria andDepartContactEqualTo(Integer value) {
			addCriterion("depart_contact =", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactNotEqualTo(Integer value) {
			addCriterion("depart_contact <>", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactGreaterThan(Integer value) {
			addCriterion("depart_contact >", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactGreaterThanOrEqualTo(Integer value) {
			addCriterion("depart_contact >=", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactLessThan(Integer value) {
			addCriterion("depart_contact <", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactLessThanOrEqualTo(Integer value) {
			addCriterion("depart_contact <=", value, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactIn(List<Integer> values) {
			addCriterion("depart_contact in", values, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactNotIn(List<Integer> values) {
			addCriterion("depart_contact not in", values, "departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactBetween(Integer value1, Integer value2) {
			addCriterion("depart_contact between", value1, value2,
					"departContact");
			return (Criteria) this;
		}

		public Criteria andDepartContactNotBetween(Integer value1,
				Integer value2) {
			addCriterion("depart_contact not between", value1, value2,
					"departContact");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneIsNull() {
			addCriterion("depart_phone is null");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneIsNotNull() {
			addCriterion("depart_phone is not null");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneEqualTo(String value) {
			addCriterion("depart_phone =", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneNotEqualTo(String value) {
			addCriterion("depart_phone <>", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneGreaterThan(String value) {
			addCriterion("depart_phone >", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("depart_phone >=", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneLessThan(String value) {
			addCriterion("depart_phone <", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneLessThanOrEqualTo(String value) {
			addCriterion("depart_phone <=", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneLike(String value) {
			addCriterion("depart_phone like", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneNotLike(String value) {
			addCriterion("depart_phone not like", value, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneIn(List<String> values) {
			addCriterion("depart_phone in", values, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneNotIn(List<String> values) {
			addCriterion("depart_phone not in", values, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneBetween(String value1, String value2) {
			addCriterion("depart_phone between", value1, value2, "departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartPhoneNotBetween(String value1, String value2) {
			addCriterion("depart_phone not between", value1, value2,
					"departPhone");
			return (Criteria) this;
		}

		public Criteria andDepartAddressIsNull() {
			addCriterion("depart_address is null");
			return (Criteria) this;
		}

		public Criteria andDepartAddressIsNotNull() {
			addCriterion("depart_address is not null");
			return (Criteria) this;
		}

		public Criteria andDepartAddressEqualTo(String value) {
			addCriterion("depart_address =", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressNotEqualTo(String value) {
			addCriterion("depart_address <>", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressGreaterThan(String value) {
			addCriterion("depart_address >", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressGreaterThanOrEqualTo(String value) {
			addCriterion("depart_address >=", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressLessThan(String value) {
			addCriterion("depart_address <", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressLessThanOrEqualTo(String value) {
			addCriterion("depart_address <=", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressLike(String value) {
			addCriterion("depart_address like", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressNotLike(String value) {
			addCriterion("depart_address not like", value, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressIn(List<String> values) {
			addCriterion("depart_address in", values, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressNotIn(List<String> values) {
			addCriterion("depart_address not in", values, "departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressBetween(String value1, String value2) {
			addCriterion("depart_address between", value1, value2,
					"departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartAddressNotBetween(String value1, String value2) {
			addCriterion("depart_address not between", value1, value2,
					"departAddress");
			return (Criteria) this;
		}

		public Criteria andDepartServiceIsNull() {
			addCriterion("depart_service is null");
			return (Criteria) this;
		}

		public Criteria andDepartServiceIsNotNull() {
			addCriterion("depart_service is not null");
			return (Criteria) this;
		}

		public Criteria andDepartServiceEqualTo(String value) {
			addCriterion("depart_service =", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceNotEqualTo(String value) {
			addCriterion("depart_service <>", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceGreaterThan(String value) {
			addCriterion("depart_service >", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceGreaterThanOrEqualTo(String value) {
			addCriterion("depart_service >=", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceLessThan(String value) {
			addCriterion("depart_service <", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceLessThanOrEqualTo(String value) {
			addCriterion("depart_service <=", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceLike(String value) {
			addCriterion("depart_service like", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceNotLike(String value) {
			addCriterion("depart_service not like", value, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceIn(List<String> values) {
			addCriterion("depart_service in", values, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceNotIn(List<String> values) {
			addCriterion("depart_service not in", values, "departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceBetween(String value1, String value2) {
			addCriterion("depart_service between", value1, value2,
					"departService");
			return (Criteria) this;
		}

		public Criteria andDepartServiceNotBetween(String value1, String value2) {
			addCriterion("depart_service not between", value1, value2,
					"departService");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table depart
	 * @mbggenerated  Tue Dec 24 20:21:21 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table depart
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 19 14:03:03 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}