package com.wuseguang.report.db.pojo;

import java.util.Date;

public class DepartmentTest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.id
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_name
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private String departName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_code
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private String departCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_contact
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private Integer departContact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_phone
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private String departPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_address
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private String departAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column depart.depart_time
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	private Date departTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.id
	 * @return  the value of depart.id
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.id
	 * @param id  the value for depart.id
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_name
	 * @return  the value of depart.depart_name
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public String getDepartName() {
		return departName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_name
	 * @param departName  the value for depart.depart_name
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartName(String departName) {
		this.departName = departName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_code
	 * @return  the value of depart.depart_code
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public String getDepartCode() {
		return departCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_code
	 * @param departCode  the value for depart.depart_code
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartCode(String departCode) {
		this.departCode = departCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_contact
	 * @return  the value of depart.depart_contact
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public Integer getDepartContact() {
		return departContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_contact
	 * @param departContact  the value for depart.depart_contact
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartContact(Integer departContact) {
		this.departContact = departContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_phone
	 * @return  the value of depart.depart_phone
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public String getDepartPhone() {
		return departPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_phone
	 * @param departPhone  the value for depart.depart_phone
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartPhone(String departPhone) {
		this.departPhone = departPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_address
	 * @return  the value of depart.depart_address
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public String getDepartAddress() {
		return departAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_address
	 * @param departAddress  the value for depart.depart_address
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartAddress(String departAddress) {
		this.departAddress = departAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column depart.depart_time
	 * @return  the value of depart.depart_time
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public Date getDepartTime() {
		return departTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column depart.depart_time
	 * @param departTime  the value for depart.depart_time
	 * @mbggenerated  Thu Dec 19 12:05:02 CST 2013
	 */
	public void setDepartTime(Date departTime) {
		this.departTime = departTime;
	}
}