package com.wuseguang.report.db.pojo;

import java.util.Date;

public class EnterpriseChina {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_name_ch
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseNameCh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_name_en
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseNameEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_name_another
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseNameAnother;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseDepartCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseBusinessAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseBusinessZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterDepart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterDepartCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_legal_person_id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Integer enterpriseLegalPersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_type
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_establish_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseEstablishDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_start_work_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseStartWorkDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseRegisterDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Integer enterpriseRegisterCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_start_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseBusinessStartDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_end_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseBusinessEndDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_register_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegisterCapitalCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_investment
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Integer enterpriseInvestment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_investment_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseInvestmentCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_paidin_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Integer enterprisePaidinCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_paidin_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterprisePaidinCapitalCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_period
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Float enterpriseBusinessPeriod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_approval_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Date enterpriseApprovalDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_business_scope
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseBusinessScope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_industry_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseIndustryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_industry_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseIndustryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_tax_code_region
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseTaxCodeRegion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_tax_code_local
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseTaxCodeLocal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_tax_code_isvat
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Boolean enterpriseTaxCodeIsvat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_has_ioright
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Boolean enterpriseHasIoright;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_iocode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseIocode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_telphone
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseTelphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_fax
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_web
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseWeb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_email
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_is_listed
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private Boolean enterpriseIsListed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_mobile
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_contact_person
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseContactPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_sic_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseSicName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_sic_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseSicCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_town
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseTown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_country
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseCountry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_scale
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseScale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_operation_state
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseOperationState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_registor_depart_level
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRegistorDepartLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_jurisdiction_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseJurisdictionDepart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_identification
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseIdentification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_remark
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_china.enterprise_remark_inner
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	private String enterpriseRemarkInner;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.id
	 * @return  the value of enterprise_china.id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.id
	 * @param id  the value for enterprise_china.id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_name_ch
	 * @return  the value of enterprise_china.enterprise_name_ch
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseNameCh() {
		return enterpriseNameCh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_name_ch
	 * @param enterpriseNameCh  the value for enterprise_china.enterprise_name_ch
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseNameCh(String enterpriseNameCh) {
		this.enterpriseNameCh = enterpriseNameCh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_name_en
	 * @return  the value of enterprise_china.enterprise_name_en
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseNameEn() {
		return enterpriseNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_name_en
	 * @param enterpriseNameEn  the value for enterprise_china.enterprise_name_en
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseNameEn(String enterpriseNameEn) {
		this.enterpriseNameEn = enterpriseNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_name_another
	 * @return  the value of enterprise_china.enterprise_name_another
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseNameAnother() {
		return enterpriseNameAnother;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_name_another
	 * @param enterpriseNameAnother  the value for enterprise_china.enterprise_name_another
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseNameAnother(String enterpriseNameAnother) {
		this.enterpriseNameAnother = enterpriseNameAnother;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_depart_code
	 * @return  the value of enterprise_china.enterprise_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseDepartCode() {
		return enterpriseDepartCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_depart_code
	 * @param enterpriseDepartCode  the value for enterprise_china.enterprise_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseDepartCode(String enterpriseDepartCode) {
		this.enterpriseDepartCode = enterpriseDepartCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_address
	 * @return  the value of enterprise_china.enterprise_business_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseBusinessAddress() {
		return enterpriseBusinessAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_address
	 * @param enterpriseBusinessAddress  the value for enterprise_china.enterprise_business_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessAddress(String enterpriseBusinessAddress) {
		this.enterpriseBusinessAddress = enterpriseBusinessAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_zipcode
	 * @return  the value of enterprise_china.enterprise_business_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseBusinessZipcode() {
		return enterpriseBusinessZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_zipcode
	 * @param enterpriseBusinessZipcode  the value for enterprise_china.enterprise_business_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessZipcode(String enterpriseBusinessZipcode) {
		this.enterpriseBusinessZipcode = enterpriseBusinessZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_address
	 * @return  the value of enterprise_china.enterprise_register_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterAddress() {
		return enterpriseRegisterAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_address
	 * @param enterpriseRegisterAddress  the value for enterprise_china.enterprise_register_address
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterAddress(String enterpriseRegisterAddress) {
		this.enterpriseRegisterAddress = enterpriseRegisterAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_zipcode
	 * @return  the value of enterprise_china.enterprise_register_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterZipcode() {
		return enterpriseRegisterZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_zipcode
	 * @param enterpriseRegisterZipcode  the value for enterprise_china.enterprise_register_zipcode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterZipcode(String enterpriseRegisterZipcode) {
		this.enterpriseRegisterZipcode = enterpriseRegisterZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_code
	 * @return  the value of enterprise_china.enterprise_register_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterCode() {
		return enterpriseRegisterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_code
	 * @param enterpriseRegisterCode  the value for enterprise_china.enterprise_register_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterCode(String enterpriseRegisterCode) {
		this.enterpriseRegisterCode = enterpriseRegisterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_depart
	 * @return  the value of enterprise_china.enterprise_register_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterDepart() {
		return enterpriseRegisterDepart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_depart
	 * @param enterpriseRegisterDepart  the value for enterprise_china.enterprise_register_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterDepart(String enterpriseRegisterDepart) {
		this.enterpriseRegisterDepart = enterpriseRegisterDepart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_depart_code
	 * @return  the value of enterprise_china.enterprise_register_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterDepartCode() {
		return enterpriseRegisterDepartCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_depart_code
	 * @param enterpriseRegisterDepartCode  the value for enterprise_china.enterprise_register_depart_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterDepartCode(
			String enterpriseRegisterDepartCode) {
		this.enterpriseRegisterDepartCode = enterpriseRegisterDepartCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_legal_person_id
	 * @return  the value of enterprise_china.enterprise_legal_person_id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Integer getEnterpriseLegalPersonId() {
		return enterpriseLegalPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_legal_person_id
	 * @param enterpriseLegalPersonId  the value for enterprise_china.enterprise_legal_person_id
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseLegalPersonId(Integer enterpriseLegalPersonId) {
		this.enterpriseLegalPersonId = enterpriseLegalPersonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_type
	 * @return  the value of enterprise_china.enterprise_type
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseType() {
		return enterpriseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_type
	 * @param enterpriseType  the value for enterprise_china.enterprise_type
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseType(String enterpriseType) {
		this.enterpriseType = enterpriseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_establish_day
	 * @return  the value of enterprise_china.enterprise_establish_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseEstablishDay() {
		return enterpriseEstablishDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_establish_day
	 * @param enterpriseEstablishDay  the value for enterprise_china.enterprise_establish_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseEstablishDay(Date enterpriseEstablishDay) {
		this.enterpriseEstablishDay = enterpriseEstablishDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_start_work_day
	 * @return  the value of enterprise_china.enterprise_start_work_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseStartWorkDay() {
		return enterpriseStartWorkDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_start_work_day
	 * @param enterpriseStartWorkDay  the value for enterprise_china.enterprise_start_work_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseStartWorkDay(Date enterpriseStartWorkDay) {
		this.enterpriseStartWorkDay = enterpriseStartWorkDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_day
	 * @return  the value of enterprise_china.enterprise_register_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseRegisterDay() {
		return enterpriseRegisterDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_day
	 * @param enterpriseRegisterDay  the value for enterprise_china.enterprise_register_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterDay(Date enterpriseRegisterDay) {
		this.enterpriseRegisterDay = enterpriseRegisterDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_capital
	 * @return  the value of enterprise_china.enterprise_register_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Integer getEnterpriseRegisterCapital() {
		return enterpriseRegisterCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_capital
	 * @param enterpriseRegisterCapital  the value for enterprise_china.enterprise_register_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterCapital(Integer enterpriseRegisterCapital) {
		this.enterpriseRegisterCapital = enterpriseRegisterCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_start_day
	 * @return  the value of enterprise_china.enterprise_business_start_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseBusinessStartDay() {
		return enterpriseBusinessStartDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_start_day
	 * @param enterpriseBusinessStartDay  the value for enterprise_china.enterprise_business_start_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessStartDay(Date enterpriseBusinessStartDay) {
		this.enterpriseBusinessStartDay = enterpriseBusinessStartDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_end_day
	 * @return  the value of enterprise_china.enterprise_business_end_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseBusinessEndDay() {
		return enterpriseBusinessEndDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_end_day
	 * @param enterpriseBusinessEndDay  the value for enterprise_china.enterprise_business_end_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessEndDay(Date enterpriseBusinessEndDay) {
		this.enterpriseBusinessEndDay = enterpriseBusinessEndDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_register_capital_currency
	 * @return  the value of enterprise_china.enterprise_register_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegisterCapitalCurrency() {
		return enterpriseRegisterCapitalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_register_capital_currency
	 * @param enterpriseRegisterCapitalCurrency  the value for enterprise_china.enterprise_register_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegisterCapitalCurrency(
			String enterpriseRegisterCapitalCurrency) {
		this.enterpriseRegisterCapitalCurrency = enterpriseRegisterCapitalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_investment
	 * @return  the value of enterprise_china.enterprise_investment
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Integer getEnterpriseInvestment() {
		return enterpriseInvestment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_investment
	 * @param enterpriseInvestment  the value for enterprise_china.enterprise_investment
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseInvestment(Integer enterpriseInvestment) {
		this.enterpriseInvestment = enterpriseInvestment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_investment_currency
	 * @return  the value of enterprise_china.enterprise_investment_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseInvestmentCurrency() {
		return enterpriseInvestmentCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_investment_currency
	 * @param enterpriseInvestmentCurrency  the value for enterprise_china.enterprise_investment_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseInvestmentCurrency(
			String enterpriseInvestmentCurrency) {
		this.enterpriseInvestmentCurrency = enterpriseInvestmentCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_paidin_capital
	 * @return  the value of enterprise_china.enterprise_paidin_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Integer getEnterprisePaidinCapital() {
		return enterprisePaidinCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_paidin_capital
	 * @param enterprisePaidinCapital  the value for enterprise_china.enterprise_paidin_capital
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterprisePaidinCapital(Integer enterprisePaidinCapital) {
		this.enterprisePaidinCapital = enterprisePaidinCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_paidin_capital_currency
	 * @return  the value of enterprise_china.enterprise_paidin_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterprisePaidinCapitalCurrency() {
		return enterprisePaidinCapitalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_paidin_capital_currency
	 * @param enterprisePaidinCapitalCurrency  the value for enterprise_china.enterprise_paidin_capital_currency
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterprisePaidinCapitalCurrency(
			String enterprisePaidinCapitalCurrency) {
		this.enterprisePaidinCapitalCurrency = enterprisePaidinCapitalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_period
	 * @return  the value of enterprise_china.enterprise_business_period
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Float getEnterpriseBusinessPeriod() {
		return enterpriseBusinessPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_period
	 * @param enterpriseBusinessPeriod  the value for enterprise_china.enterprise_business_period
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessPeriod(Float enterpriseBusinessPeriod) {
		this.enterpriseBusinessPeriod = enterpriseBusinessPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_approval_day
	 * @return  the value of enterprise_china.enterprise_approval_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Date getEnterpriseApprovalDay() {
		return enterpriseApprovalDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_approval_day
	 * @param enterpriseApprovalDay  the value for enterprise_china.enterprise_approval_day
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseApprovalDay(Date enterpriseApprovalDay) {
		this.enterpriseApprovalDay = enterpriseApprovalDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_business_scope
	 * @return  the value of enterprise_china.enterprise_business_scope
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseBusinessScope() {
		return enterpriseBusinessScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_business_scope
	 * @param enterpriseBusinessScope  the value for enterprise_china.enterprise_business_scope
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseBusinessScope(String enterpriseBusinessScope) {
		this.enterpriseBusinessScope = enterpriseBusinessScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_industry_code
	 * @return  the value of enterprise_china.enterprise_industry_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseIndustryCode() {
		return enterpriseIndustryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_industry_code
	 * @param enterpriseIndustryCode  the value for enterprise_china.enterprise_industry_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseIndustryCode(String enterpriseIndustryCode) {
		this.enterpriseIndustryCode = enterpriseIndustryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_industry_name
	 * @return  the value of enterprise_china.enterprise_industry_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseIndustryName() {
		return enterpriseIndustryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_industry_name
	 * @param enterpriseIndustryName  the value for enterprise_china.enterprise_industry_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseIndustryName(String enterpriseIndustryName) {
		this.enterpriseIndustryName = enterpriseIndustryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_tax_code_region
	 * @return  the value of enterprise_china.enterprise_tax_code_region
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseTaxCodeRegion() {
		return enterpriseTaxCodeRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_tax_code_region
	 * @param enterpriseTaxCodeRegion  the value for enterprise_china.enterprise_tax_code_region
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseTaxCodeRegion(String enterpriseTaxCodeRegion) {
		this.enterpriseTaxCodeRegion = enterpriseTaxCodeRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_tax_code_local
	 * @return  the value of enterprise_china.enterprise_tax_code_local
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseTaxCodeLocal() {
		return enterpriseTaxCodeLocal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_tax_code_local
	 * @param enterpriseTaxCodeLocal  the value for enterprise_china.enterprise_tax_code_local
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseTaxCodeLocal(String enterpriseTaxCodeLocal) {
		this.enterpriseTaxCodeLocal = enterpriseTaxCodeLocal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_tax_code_isvat
	 * @return  the value of enterprise_china.enterprise_tax_code_isvat
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Boolean getEnterpriseTaxCodeIsvat() {
		return enterpriseTaxCodeIsvat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_tax_code_isvat
	 * @param enterpriseTaxCodeIsvat  the value for enterprise_china.enterprise_tax_code_isvat
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseTaxCodeIsvat(Boolean enterpriseTaxCodeIsvat) {
		this.enterpriseTaxCodeIsvat = enterpriseTaxCodeIsvat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_has_ioright
	 * @return  the value of enterprise_china.enterprise_has_ioright
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Boolean getEnterpriseHasIoright() {
		return enterpriseHasIoright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_has_ioright
	 * @param enterpriseHasIoright  the value for enterprise_china.enterprise_has_ioright
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseHasIoright(Boolean enterpriseHasIoright) {
		this.enterpriseHasIoright = enterpriseHasIoright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_iocode
	 * @return  the value of enterprise_china.enterprise_iocode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseIocode() {
		return enterpriseIocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_iocode
	 * @param enterpriseIocode  the value for enterprise_china.enterprise_iocode
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseIocode(String enterpriseIocode) {
		this.enterpriseIocode = enterpriseIocode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_telphone
	 * @return  the value of enterprise_china.enterprise_telphone
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseTelphone() {
		return enterpriseTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_telphone
	 * @param enterpriseTelphone  the value for enterprise_china.enterprise_telphone
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseTelphone(String enterpriseTelphone) {
		this.enterpriseTelphone = enterpriseTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_fax
	 * @return  the value of enterprise_china.enterprise_fax
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseFax() {
		return enterpriseFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_fax
	 * @param enterpriseFax  the value for enterprise_china.enterprise_fax
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseFax(String enterpriseFax) {
		this.enterpriseFax = enterpriseFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_web
	 * @return  the value of enterprise_china.enterprise_web
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseWeb() {
		return enterpriseWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_web
	 * @param enterpriseWeb  the value for enterprise_china.enterprise_web
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseWeb(String enterpriseWeb) {
		this.enterpriseWeb = enterpriseWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_email
	 * @return  the value of enterprise_china.enterprise_email
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseEmail() {
		return enterpriseEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_email
	 * @param enterpriseEmail  the value for enterprise_china.enterprise_email
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseEmail(String enterpriseEmail) {
		this.enterpriseEmail = enterpriseEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_is_listed
	 * @return  the value of enterprise_china.enterprise_is_listed
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public Boolean getEnterpriseIsListed() {
		return enterpriseIsListed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_is_listed
	 * @param enterpriseIsListed  the value for enterprise_china.enterprise_is_listed
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseIsListed(Boolean enterpriseIsListed) {
		this.enterpriseIsListed = enterpriseIsListed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_mobile
	 * @return  the value of enterprise_china.enterprise_mobile
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseMobile() {
		return enterpriseMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_mobile
	 * @param enterpriseMobile  the value for enterprise_china.enterprise_mobile
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseMobile(String enterpriseMobile) {
		this.enterpriseMobile = enterpriseMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_contact_person
	 * @return  the value of enterprise_china.enterprise_contact_person
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseContactPerson() {
		return enterpriseContactPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_contact_person
	 * @param enterpriseContactPerson  the value for enterprise_china.enterprise_contact_person
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseContactPerson(String enterpriseContactPerson) {
		this.enterpriseContactPerson = enterpriseContactPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_sic_name
	 * @return  the value of enterprise_china.enterprise_sic_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseSicName() {
		return enterpriseSicName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_sic_name
	 * @param enterpriseSicName  the value for enterprise_china.enterprise_sic_name
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseSicName(String enterpriseSicName) {
		this.enterpriseSicName = enterpriseSicName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_sic_code
	 * @return  the value of enterprise_china.enterprise_sic_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseSicCode() {
		return enterpriseSicCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_sic_code
	 * @param enterpriseSicCode  the value for enterprise_china.enterprise_sic_code
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseSicCode(String enterpriseSicCode) {
		this.enterpriseSicCode = enterpriseSicCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_town
	 * @return  the value of enterprise_china.enterprise_town
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseTown() {
		return enterpriseTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_town
	 * @param enterpriseTown  the value for enterprise_china.enterprise_town
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseTown(String enterpriseTown) {
		this.enterpriseTown = enterpriseTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_country
	 * @return  the value of enterprise_china.enterprise_country
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseCountry() {
		return enterpriseCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_country
	 * @param enterpriseCountry  the value for enterprise_china.enterprise_country
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseCountry(String enterpriseCountry) {
		this.enterpriseCountry = enterpriseCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_scale
	 * @return  the value of enterprise_china.enterprise_scale
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseScale() {
		return enterpriseScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_scale
	 * @param enterpriseScale  the value for enterprise_china.enterprise_scale
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseScale(String enterpriseScale) {
		this.enterpriseScale = enterpriseScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_operation_state
	 * @return  the value of enterprise_china.enterprise_operation_state
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseOperationState() {
		return enterpriseOperationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_operation_state
	 * @param enterpriseOperationState  the value for enterprise_china.enterprise_operation_state
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseOperationState(String enterpriseOperationState) {
		this.enterpriseOperationState = enterpriseOperationState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_registor_depart_level
	 * @return  the value of enterprise_china.enterprise_registor_depart_level
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRegistorDepartLevel() {
		return enterpriseRegistorDepartLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_registor_depart_level
	 * @param enterpriseRegistorDepartLevel  the value for enterprise_china.enterprise_registor_depart_level
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRegistorDepartLevel(
			String enterpriseRegistorDepartLevel) {
		this.enterpriseRegistorDepartLevel = enterpriseRegistorDepartLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_jurisdiction_depart
	 * @return  the value of enterprise_china.enterprise_jurisdiction_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseJurisdictionDepart() {
		return enterpriseJurisdictionDepart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_jurisdiction_depart
	 * @param enterpriseJurisdictionDepart  the value for enterprise_china.enterprise_jurisdiction_depart
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseJurisdictionDepart(
			String enterpriseJurisdictionDepart) {
		this.enterpriseJurisdictionDepart = enterpriseJurisdictionDepart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_identification
	 * @return  the value of enterprise_china.enterprise_identification
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseIdentification() {
		return enterpriseIdentification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_identification
	 * @param enterpriseIdentification  the value for enterprise_china.enterprise_identification
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseIdentification(String enterpriseIdentification) {
		this.enterpriseIdentification = enterpriseIdentification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_remark
	 * @return  the value of enterprise_china.enterprise_remark
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRemark() {
		return enterpriseRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_remark
	 * @param enterpriseRemark  the value for enterprise_china.enterprise_remark
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRemark(String enterpriseRemark) {
		this.enterpriseRemark = enterpriseRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_china.enterprise_remark_inner
	 * @return  the value of enterprise_china.enterprise_remark_inner
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public String getEnterpriseRemarkInner() {
		return enterpriseRemarkInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_china.enterprise_remark_inner
	 * @param enterpriseRemarkInner  the value for enterprise_china.enterprise_remark_inner
	 * @mbggenerated  Sat Dec 28 19:40:10 CST 2013
	 */
	public void setEnterpriseRemarkInner(String enterpriseRemarkInner) {
		this.enterpriseRemarkInner = enterpriseRemarkInner;
	}
}