package com.wuseguang.report.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EntShareholderExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public EntShareholderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) return;
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) return;
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) return;
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitIsNull() {
            addCriterion("shareholder_currency_unit is null");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitIsNotNull() {
            addCriterion("shareholder_currency_unit is not null");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitEqualTo(String value) {
            addCriterion("shareholder_currency_unit =", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitNotEqualTo(String value) {
            addCriterion("shareholder_currency_unit <>", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitGreaterThan(String value) {
            addCriterion("shareholder_currency_unit >", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitGreaterThanOrEqualTo(String value) {
            addCriterion("shareholder_currency_unit >=", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitLessThan(String value) {
            addCriterion("shareholder_currency_unit <", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitLessThanOrEqualTo(String value) {
            addCriterion("shareholder_currency_unit <=", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitLike(String value) {
            addCriterion("shareholder_currency_unit like", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitNotLike(String value) {
            addCriterion("shareholder_currency_unit not like", value, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitIn(List<String> values) {
            addCriterion("shareholder_currency_unit in", values, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitNotIn(List<String> values) {
            addCriterion("shareholder_currency_unit not in", values, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitBetween(String value1, String value2) {
            addCriterion("shareholder_currency_unit between", value1, value2, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyUnitNotBetween(String value1, String value2) {
            addCriterion("shareholder_currency_unit not between", value1, value2, "shareholderCurrencyUnit");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeIsNull() {
            addCriterion("shareholder_currency_type is null");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeIsNotNull() {
            addCriterion("shareholder_currency_type is not null");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeEqualTo(String value) {
            addCriterion("shareholder_currency_type =", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeNotEqualTo(String value) {
            addCriterion("shareholder_currency_type <>", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeGreaterThan(String value) {
            addCriterion("shareholder_currency_type >", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("shareholder_currency_type >=", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeLessThan(String value) {
            addCriterion("shareholder_currency_type <", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("shareholder_currency_type <=", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeLike(String value) {
            addCriterion("shareholder_currency_type like", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeNotLike(String value) {
            addCriterion("shareholder_currency_type not like", value, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeIn(List<String> values) {
            addCriterion("shareholder_currency_type in", values, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeNotIn(List<String> values) {
            addCriterion("shareholder_currency_type not in", values, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeBetween(String value1, String value2) {
            addCriterion("shareholder_currency_type between", value1, value2, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("shareholder_currency_type not between", value1, value2, "shareholderCurrencyType");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeIsNull() {
            addCriterion("shareholder_infotime is null");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeIsNotNull() {
            addCriterion("shareholder_infotime is not null");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeEqualTo(Date value) {
            addCriterionForJDBCDate("shareholder_infotime =", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("shareholder_infotime <>", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeGreaterThan(Date value) {
            addCriterionForJDBCDate("shareholder_infotime >", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("shareholder_infotime >=", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeLessThan(Date value) {
            addCriterionForJDBCDate("shareholder_infotime <", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("shareholder_infotime <=", value, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeIn(List<Date> values) {
            addCriterionForJDBCDate("shareholder_infotime in", values, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("shareholder_infotime not in", values, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("shareholder_infotime between", value1, value2, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andShareholderInfotimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("shareholder_infotime not between", value1, value2, "shareholderInfotime");
            return (Criteria) this;
        }

        public Criteria andEntIdIsNull() {
            addCriterion("ent_id is null");
            return (Criteria) this;
        }

        public Criteria andEntIdIsNotNull() {
            addCriterion("ent_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntIdEqualTo(Integer value) {
            addCriterion("ent_id =", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotEqualTo(Integer value) {
            addCriterion("ent_id <>", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThan(Integer value) {
            addCriterion("ent_id >", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ent_id >=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThan(Integer value) {
            addCriterion("ent_id <", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThanOrEqualTo(Integer value) {
            addCriterion("ent_id <=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdIn(List<Integer> values) {
            addCriterion("ent_id in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotIn(List<Integer> values) {
            addCriterion("ent_id not in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdBetween(Integer value1, Integer value2) {
            addCriterion("ent_id between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ent_id not between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Integer value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Integer value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Integer value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Integer value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Integer> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Integer> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeIsNull() {
            addCriterion("shareholder_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeIsNotNull() {
            addCriterion("shareholder_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeEqualTo(Date value) {
            addCriterion("shareholder_updatetime =", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeNotEqualTo(Date value) {
            addCriterion("shareholder_updatetime <>", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeGreaterThan(Date value) {
            addCriterion("shareholder_updatetime >", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shareholder_updatetime >=", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeLessThan(Date value) {
            addCriterion("shareholder_updatetime <", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("shareholder_updatetime <=", value, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeIn(List<Date> values) {
            addCriterion("shareholder_updatetime in", values, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeNotIn(List<Date> values) {
            addCriterion("shareholder_updatetime not in", values, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("shareholder_updatetime between", value1, value2, "shareholderUpdatetime");
            return (Criteria) this;
        }

        public Criteria andShareholderUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("shareholder_updatetime not between", value1, value2, "shareholderUpdatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ent_shareholder
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 09 22:05:34 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ent_shareholder
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}