package com.wuseguang.report.db.pojo;

public class EntShareholderList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.sharehodler_name
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String sharehodlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_contribute
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Float shareholderContribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderCurrencyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderCurrencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_contribute_ratio
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Float shareholderContributeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder_list.shareholder_background
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderBackground;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.id
     *
     * @return the value of ent_shareholder_list.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.id
     *
     * @param id the value for ent_shareholder_list.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_type
     *
     * @return the value of ent_shareholder_list.shareholder_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderType() {
        return shareholderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_type
     *
     * @param shareholderType the value for ent_shareholder_list.shareholder_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderType(String shareholderType) {
        this.shareholderType = shareholderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.sharehodler_name
     *
     * @return the value of ent_shareholder_list.sharehodler_name
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getSharehodlerName() {
        return sharehodlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.sharehodler_name
     *
     * @param sharehodlerName the value for ent_shareholder_list.sharehodler_name
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setSharehodlerName(String sharehodlerName) {
        this.sharehodlerName = sharehodlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_contribute
     *
     * @return the value of ent_shareholder_list.shareholder_contribute
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Float getShareholderContribute() {
        return shareholderContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_contribute
     *
     * @param shareholderContribute the value for ent_shareholder_list.shareholder_contribute
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderContribute(Float shareholderContribute) {
        this.shareholderContribute = shareholderContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_currency_unit
     *
     * @return the value of ent_shareholder_list.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderCurrencyUnit() {
        return shareholderCurrencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_currency_unit
     *
     * @param shareholderCurrencyUnit the value for ent_shareholder_list.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderCurrencyUnit(String shareholderCurrencyUnit) {
        this.shareholderCurrencyUnit = shareholderCurrencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_currency_type
     *
     * @return the value of ent_shareholder_list.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderCurrencyType() {
        return shareholderCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_currency_type
     *
     * @param shareholderCurrencyType the value for ent_shareholder_list.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderCurrencyType(String shareholderCurrencyType) {
        this.shareholderCurrencyType = shareholderCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_contribute_ratio
     *
     * @return the value of ent_shareholder_list.shareholder_contribute_ratio
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Float getShareholderContributeRatio() {
        return shareholderContributeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_contribute_ratio
     *
     * @param shareholderContributeRatio the value for ent_shareholder_list.shareholder_contribute_ratio
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderContributeRatio(Float shareholderContributeRatio) {
        this.shareholderContributeRatio = shareholderContributeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder_list.shareholder_background
     *
     * @return the value of ent_shareholder_list.shareholder_background
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderBackground() {
        return shareholderBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder_list.shareholder_background
     *
     * @param shareholderBackground the value for ent_shareholder_list.shareholder_background
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderBackground(String shareholderBackground) {
        this.shareholderBackground = shareholderBackground;
    }
}