package com.wuseguang.report.db.pojo;

import java.util.Date;

public class EntShareholder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderCurrencyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private String shareholderCurrencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.shareholder_infotime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Date shareholderInfotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.ent_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Integer entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.creator_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_shareholder.shareholder_updatetime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    private Date shareholderUpdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.id
     *
     * @return the value of ent_shareholder.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.id
     *
     * @param id the value for ent_shareholder.id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.shareholder_currency_unit
     *
     * @return the value of ent_shareholder.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderCurrencyUnit() {
        return shareholderCurrencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.shareholder_currency_unit
     *
     * @param shareholderCurrencyUnit the value for ent_shareholder.shareholder_currency_unit
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderCurrencyUnit(String shareholderCurrencyUnit) {
        this.shareholderCurrencyUnit = shareholderCurrencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.shareholder_currency_type
     *
     * @return the value of ent_shareholder.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public String getShareholderCurrencyType() {
        return shareholderCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.shareholder_currency_type
     *
     * @param shareholderCurrencyType the value for ent_shareholder.shareholder_currency_type
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderCurrencyType(String shareholderCurrencyType) {
        this.shareholderCurrencyType = shareholderCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.shareholder_infotime
     *
     * @return the value of ent_shareholder.shareholder_infotime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Date getShareholderInfotime() {
        return shareholderInfotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.shareholder_infotime
     *
     * @param shareholderInfotime the value for ent_shareholder.shareholder_infotime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderInfotime(Date shareholderInfotime) {
        this.shareholderInfotime = shareholderInfotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.ent_id
     *
     * @return the value of ent_shareholder.ent_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Integer getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.ent_id
     *
     * @param entId the value for ent_shareholder.ent_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setEntId(Integer entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.creator_id
     *
     * @return the value of ent_shareholder.creator_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.creator_id
     *
     * @param creatorId the value for ent_shareholder.creator_id
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_shareholder.shareholder_updatetime
     *
     * @return the value of ent_shareholder.shareholder_updatetime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public Date getShareholderUpdatetime() {
        return shareholderUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_shareholder.shareholder_updatetime
     *
     * @param shareholderUpdatetime the value for ent_shareholder.shareholder_updatetime
     *
     * @mbggenerated Thu Jan 09 22:05:34 CST 2014
     */
    public void setShareholderUpdatetime(Date shareholderUpdatetime) {
        this.shareholderUpdatetime = shareholderUpdatetime;
    }
}