package com.wuseguang.report.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonExample extends BaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public PersonExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null)
				return;
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null)
				return;
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null)
				return;
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPersonNameIsNull() {
			addCriterion("person_name is null");
			return (Criteria) this;
		}

		public Criteria andPersonNameIsNotNull() {
			addCriterion("person_name is not null");
			return (Criteria) this;
		}

		public Criteria andPersonNameEqualTo(String value) {
			addCriterion("person_name =", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameNotEqualTo(String value) {
			addCriterion("person_name <>", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameGreaterThan(String value) {
			addCriterion("person_name >", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameGreaterThanOrEqualTo(String value) {
			addCriterion("person_name >=", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameLessThan(String value) {
			addCriterion("person_name <", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameLessThanOrEqualTo(String value) {
			addCriterion("person_name <=", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameLike(String value) {
			addCriterion("person_name like", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameNotLike(String value) {
			addCriterion("person_name not like", value, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameIn(List<String> values) {
			addCriterion("person_name in", values, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameNotIn(List<String> values) {
			addCriterion("person_name not in", values, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameBetween(String value1, String value2) {
			addCriterion("person_name between", value1, value2, "personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameNotBetween(String value1, String value2) {
			addCriterion("person_name not between", value1, value2,
					"personName");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnIsNull() {
			addCriterion("person_name_en is null");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnIsNotNull() {
			addCriterion("person_name_en is not null");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnEqualTo(String value) {
			addCriterion("person_name_en =", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnNotEqualTo(String value) {
			addCriterion("person_name_en <>", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnGreaterThan(String value) {
			addCriterion("person_name_en >", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnGreaterThanOrEqualTo(String value) {
			addCriterion("person_name_en >=", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnLessThan(String value) {
			addCriterion("person_name_en <", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnLessThanOrEqualTo(String value) {
			addCriterion("person_name_en <=", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnLike(String value) {
			addCriterion("person_name_en like", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnNotLike(String value) {
			addCriterion("person_name_en not like", value, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnIn(List<String> values) {
			addCriterion("person_name_en in", values, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnNotIn(List<String> values) {
			addCriterion("person_name_en not in", values, "personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnBetween(String value1, String value2) {
			addCriterion("person_name_en between", value1, value2,
					"personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonNameEnNotBetween(String value1, String value2) {
			addCriterion("person_name_en not between", value1, value2,
					"personNameEn");
			return (Criteria) this;
		}

		public Criteria andPersonRegionIsNull() {
			addCriterion("person_region is null");
			return (Criteria) this;
		}

		public Criteria andPersonRegionIsNotNull() {
			addCriterion("person_region is not null");
			return (Criteria) this;
		}

		public Criteria andPersonRegionEqualTo(String value) {
			addCriterion("person_region =", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionNotEqualTo(String value) {
			addCriterion("person_region <>", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionGreaterThan(String value) {
			addCriterion("person_region >", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionGreaterThanOrEqualTo(String value) {
			addCriterion("person_region >=", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionLessThan(String value) {
			addCriterion("person_region <", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionLessThanOrEqualTo(String value) {
			addCriterion("person_region <=", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionLike(String value) {
			addCriterion("person_region like", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionNotLike(String value) {
			addCriterion("person_region not like", value, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionIn(List<String> values) {
			addCriterion("person_region in", values, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionNotIn(List<String> values) {
			addCriterion("person_region not in", values, "personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionBetween(String value1, String value2) {
			addCriterion("person_region between", value1, value2,
					"personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonRegionNotBetween(String value1, String value2) {
			addCriterion("person_region not between", value1, value2,
					"personRegion");
			return (Criteria) this;
		}

		public Criteria andPersonNationIsNull() {
			addCriterion("person_nation is null");
			return (Criteria) this;
		}

		public Criteria andPersonNationIsNotNull() {
			addCriterion("person_nation is not null");
			return (Criteria) this;
		}

		public Criteria andPersonNationEqualTo(String value) {
			addCriterion("person_nation =", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationNotEqualTo(String value) {
			addCriterion("person_nation <>", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationGreaterThan(String value) {
			addCriterion("person_nation >", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationGreaterThanOrEqualTo(String value) {
			addCriterion("person_nation >=", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationLessThan(String value) {
			addCriterion("person_nation <", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationLessThanOrEqualTo(String value) {
			addCriterion("person_nation <=", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationLike(String value) {
			addCriterion("person_nation like", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationNotLike(String value) {
			addCriterion("person_nation not like", value, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationIn(List<String> values) {
			addCriterion("person_nation in", values, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationNotIn(List<String> values) {
			addCriterion("person_nation not in", values, "personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationBetween(String value1, String value2) {
			addCriterion("person_nation between", value1, value2,
					"personNation");
			return (Criteria) this;
		}

		public Criteria andPersonNationNotBetween(String value1, String value2) {
			addCriterion("person_nation not between", value1, value2,
					"personNation");
			return (Criteria) this;
		}

		public Criteria andPersonPassportIsNull() {
			addCriterion("person_passport is null");
			return (Criteria) this;
		}

		public Criteria andPersonPassportIsNotNull() {
			addCriterion("person_passport is not null");
			return (Criteria) this;
		}

		public Criteria andPersonPassportEqualTo(String value) {
			addCriterion("person_passport =", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportNotEqualTo(String value) {
			addCriterion("person_passport <>", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportGreaterThan(String value) {
			addCriterion("person_passport >", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportGreaterThanOrEqualTo(String value) {
			addCriterion("person_passport >=", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportLessThan(String value) {
			addCriterion("person_passport <", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportLessThanOrEqualTo(String value) {
			addCriterion("person_passport <=", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportLike(String value) {
			addCriterion("person_passport like", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportNotLike(String value) {
			addCriterion("person_passport not like", value, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportIn(List<String> values) {
			addCriterion("person_passport in", values, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportNotIn(List<String> values) {
			addCriterion("person_passport not in", values, "personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportBetween(String value1, String value2) {
			addCriterion("person_passport between", value1, value2,
					"personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonPassportNotBetween(String value1, String value2) {
			addCriterion("person_passport not between", value1, value2,
					"personPassport");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardIsNull() {
			addCriterion("person_idcard is null");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardIsNotNull() {
			addCriterion("person_idcard is not null");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardEqualTo(String value) {
			addCriterion("person_idcard =", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardNotEqualTo(String value) {
			addCriterion("person_idcard <>", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardGreaterThan(String value) {
			addCriterion("person_idcard >", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardGreaterThanOrEqualTo(String value) {
			addCriterion("person_idcard >=", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardLessThan(String value) {
			addCriterion("person_idcard <", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardLessThanOrEqualTo(String value) {
			addCriterion("person_idcard <=", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardLike(String value) {
			addCriterion("person_idcard like", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardNotLike(String value) {
			addCriterion("person_idcard not like", value, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardIn(List<String> values) {
			addCriterion("person_idcard in", values, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardNotIn(List<String> values) {
			addCriterion("person_idcard not in", values, "personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardBetween(String value1, String value2) {
			addCriterion("person_idcard between", value1, value2,
					"personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonIdcardNotBetween(String value1, String value2) {
			addCriterion("person_idcard not between", value1, value2,
					"personIdcard");
			return (Criteria) this;
		}

		public Criteria andPersonSexIsNull() {
			addCriterion("person_sex is null");
			return (Criteria) this;
		}

		public Criteria andPersonSexIsNotNull() {
			addCriterion("person_sex is not null");
			return (Criteria) this;
		}

		public Criteria andPersonSexEqualTo(String value) {
			addCriterion("person_sex =", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexNotEqualTo(String value) {
			addCriterion("person_sex <>", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexGreaterThan(String value) {
			addCriterion("person_sex >", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexGreaterThanOrEqualTo(String value) {
			addCriterion("person_sex >=", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexLessThan(String value) {
			addCriterion("person_sex <", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexLessThanOrEqualTo(String value) {
			addCriterion("person_sex <=", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexLike(String value) {
			addCriterion("person_sex like", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexNotLike(String value) {
			addCriterion("person_sex not like", value, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexIn(List<String> values) {
			addCriterion("person_sex in", values, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexNotIn(List<String> values) {
			addCriterion("person_sex not in", values, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexBetween(String value1, String value2) {
			addCriterion("person_sex between", value1, value2, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonSexNotBetween(String value1, String value2) {
			addCriterion("person_sex not between", value1, value2, "personSex");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayIsNull() {
			addCriterion("person_birthday is null");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayIsNotNull() {
			addCriterion("person_birthday is not null");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayEqualTo(Date value) {
			addCriterion("person_birthday =", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayNotEqualTo(Date value) {
			addCriterion("person_birthday <>", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayGreaterThan(Date value) {
			addCriterion("person_birthday >", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("person_birthday >=", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayLessThan(Date value) {
			addCriterion("person_birthday <", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("person_birthday <=", value, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayIn(List<Date> values) {
			addCriterion("person_birthday in", values, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayNotIn(List<Date> values) {
			addCriterion("person_birthday not in", values, "personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayBetween(Date value1, Date value2) {
			addCriterion("person_birthday between", value1, value2,
					"personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("person_birthday not between", value1, value2,
					"personBirthday");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelIsNull() {
			addCriterion("person_education_level is null");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelIsNotNull() {
			addCriterion("person_education_level is not null");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelEqualTo(String value) {
			addCriterion("person_education_level =", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelNotEqualTo(String value) {
			addCriterion("person_education_level <>", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelGreaterThan(String value) {
			addCriterion("person_education_level >", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelGreaterThanOrEqualTo(String value) {
			addCriterion("person_education_level >=", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelLessThan(String value) {
			addCriterion("person_education_level <", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelLessThanOrEqualTo(String value) {
			addCriterion("person_education_level <=", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelLike(String value) {
			addCriterion("person_education_level like", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelNotLike(String value) {
			addCriterion("person_education_level not like", value,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelIn(List<String> values) {
			addCriterion("person_education_level in", values,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelNotIn(List<String> values) {
			addCriterion("person_education_level not in", values,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelBetween(String value1,
				String value2) {
			addCriterion("person_education_level between", value1, value2,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonEducationLevelNotBetween(String value1,
				String value2) {
			addCriterion("person_education_level not between", value1, value2,
					"personEducationLevel");
			return (Criteria) this;
		}

		public Criteria andPersonAddressIsNull() {
			addCriterion("person_address is null");
			return (Criteria) this;
		}

		public Criteria andPersonAddressIsNotNull() {
			addCriterion("person_address is not null");
			return (Criteria) this;
		}

		public Criteria andPersonAddressEqualTo(String value) {
			addCriterion("person_address =", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressNotEqualTo(String value) {
			addCriterion("person_address <>", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressGreaterThan(String value) {
			addCriterion("person_address >", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressGreaterThanOrEqualTo(String value) {
			addCriterion("person_address >=", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressLessThan(String value) {
			addCriterion("person_address <", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressLessThanOrEqualTo(String value) {
			addCriterion("person_address <=", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressLike(String value) {
			addCriterion("person_address like", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressNotLike(String value) {
			addCriterion("person_address not like", value, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressIn(List<String> values) {
			addCriterion("person_address in", values, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressNotIn(List<String> values) {
			addCriterion("person_address not in", values, "personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressBetween(String value1, String value2) {
			addCriterion("person_address between", value1, value2,
					"personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonAddressNotBetween(String value1, String value2) {
			addCriterion("person_address not between", value1, value2,
					"personAddress");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyIsNull() {
			addCriterion("person_specialty is null");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyIsNotNull() {
			addCriterion("person_specialty is not null");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyEqualTo(String value) {
			addCriterion("person_specialty =", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyNotEqualTo(String value) {
			addCriterion("person_specialty <>", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyGreaterThan(String value) {
			addCriterion("person_specialty >", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyGreaterThanOrEqualTo(String value) {
			addCriterion("person_specialty >=", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyLessThan(String value) {
			addCriterion("person_specialty <", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyLessThanOrEqualTo(String value) {
			addCriterion("person_specialty <=", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyLike(String value) {
			addCriterion("person_specialty like", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyNotLike(String value) {
			addCriterion("person_specialty not like", value, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyIn(List<String> values) {
			addCriterion("person_specialty in", values, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyNotIn(List<String> values) {
			addCriterion("person_specialty not in", values, "personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyBetween(String value1, String value2) {
			addCriterion("person_specialty between", value1, value2,
					"personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonSpecialtyNotBetween(String value1,
				String value2) {
			addCriterion("person_specialty not between", value1, value2,
					"personSpecialty");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceIsNull() {
			addCriterion("person_work_experience is null");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceIsNotNull() {
			addCriterion("person_work_experience is not null");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceEqualTo(String value) {
			addCriterion("person_work_experience =", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceNotEqualTo(String value) {
			addCriterion("person_work_experience <>", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceGreaterThan(String value) {
			addCriterion("person_work_experience >", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceGreaterThanOrEqualTo(String value) {
			addCriterion("person_work_experience >=", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceLessThan(String value) {
			addCriterion("person_work_experience <", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceLessThanOrEqualTo(String value) {
			addCriterion("person_work_experience <=", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceLike(String value) {
			addCriterion("person_work_experience like", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceNotLike(String value) {
			addCriterion("person_work_experience not like", value,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceIn(List<String> values) {
			addCriterion("person_work_experience in", values,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceNotIn(List<String> values) {
			addCriterion("person_work_experience not in", values,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceBetween(String value1,
				String value2) {
			addCriterion("person_work_experience between", value1, value2,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonWorkExperienceNotBetween(String value1,
				String value2) {
			addCriterion("person_work_experience not between", value1, value2,
					"personWorkExperience");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoIsNull() {
			addCriterion("person_pulic_info is null");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoIsNotNull() {
			addCriterion("person_pulic_info is not null");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoEqualTo(String value) {
			addCriterion("person_pulic_info =", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoNotEqualTo(String value) {
			addCriterion("person_pulic_info <>", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoGreaterThan(String value) {
			addCriterion("person_pulic_info >", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoGreaterThanOrEqualTo(String value) {
			addCriterion("person_pulic_info >=", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoLessThan(String value) {
			addCriterion("person_pulic_info <", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoLessThanOrEqualTo(String value) {
			addCriterion("person_pulic_info <=", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoLike(String value) {
			addCriterion("person_pulic_info like", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoNotLike(String value) {
			addCriterion("person_pulic_info not like", value, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoIn(List<String> values) {
			addCriterion("person_pulic_info in", values, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoNotIn(List<String> values) {
			addCriterion("person_pulic_info not in", values, "personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoBetween(String value1, String value2) {
			addCriterion("person_pulic_info between", value1, value2,
					"personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonPulicInfoNotBetween(String value1,
				String value2) {
			addCriterion("person_pulic_info not between", value1, value2,
					"personPulicInfo");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordIsNull() {
			addCriterion("person_bad_record is null");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordIsNotNull() {
			addCriterion("person_bad_record is not null");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordEqualTo(String value) {
			addCriterion("person_bad_record =", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordNotEqualTo(String value) {
			addCriterion("person_bad_record <>", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordGreaterThan(String value) {
			addCriterion("person_bad_record >", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordGreaterThanOrEqualTo(String value) {
			addCriterion("person_bad_record >=", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordLessThan(String value) {
			addCriterion("person_bad_record <", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordLessThanOrEqualTo(String value) {
			addCriterion("person_bad_record <=", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordLike(String value) {
			addCriterion("person_bad_record like", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordNotLike(String value) {
			addCriterion("person_bad_record not like", value, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordIn(List<String> values) {
			addCriterion("person_bad_record in", values, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordNotIn(List<String> values) {
			addCriterion("person_bad_record not in", values, "personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordBetween(String value1, String value2) {
			addCriterion("person_bad_record between", value1, value2,
					"personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonBadRecordNotBetween(String value1,
				String value2) {
			addCriterion("person_bad_record not between", value1, value2,
					"personBadRecord");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkIsNull() {
			addCriterion("person_remark is null");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkIsNotNull() {
			addCriterion("person_remark is not null");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkEqualTo(String value) {
			addCriterion("person_remark =", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkNotEqualTo(String value) {
			addCriterion("person_remark <>", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkGreaterThan(String value) {
			addCriterion("person_remark >", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("person_remark >=", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkLessThan(String value) {
			addCriterion("person_remark <", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkLessThanOrEqualTo(String value) {
			addCriterion("person_remark <=", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkLike(String value) {
			addCriterion("person_remark like", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkNotLike(String value) {
			addCriterion("person_remark not like", value, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkIn(List<String> values) {
			addCriterion("person_remark in", values, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkNotIn(List<String> values) {
			addCriterion("person_remark not in", values, "personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkBetween(String value1, String value2) {
			addCriterion("person_remark between", value1, value2,
					"personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonRemarkNotBetween(String value1, String value2) {
			addCriterion("person_remark not between", value1, value2,
					"personRemark");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdIsNull() {
			addCriterion("person_creator_id is null");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdIsNotNull() {
			addCriterion("person_creator_id is not null");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdEqualTo(Integer value) {
			addCriterion("person_creator_id =", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdNotEqualTo(Integer value) {
			addCriterion("person_creator_id <>", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdGreaterThan(Integer value) {
			addCriterion("person_creator_id >", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("person_creator_id >=", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdLessThan(Integer value) {
			addCriterion("person_creator_id <", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdLessThanOrEqualTo(Integer value) {
			addCriterion("person_creator_id <=", value, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdIn(List<Integer> values) {
			addCriterion("person_creator_id in", values, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdNotIn(List<Integer> values) {
			addCriterion("person_creator_id not in", values, "personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdBetween(Integer value1, Integer value2) {
			addCriterion("person_creator_id between", value1, value2,
					"personCreatorId");
			return (Criteria) this;
		}

		public Criteria andPersonCreatorIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("person_creator_id not between", value1, value2,
					"personCreatorId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table person
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 28 14:50:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}