package com.wuseguang.report.db.pojo;

import java.util.Date;

public class Person {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_name
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_name_en
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personNameEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_region
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personRegion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_nation
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personNation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_passport
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personPassport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_idcard
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personIdcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_sex
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_birthday
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private Date personBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_education_level
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personEducationLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_address
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_specialty
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personSpecialty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_work_experience
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personWorkExperience;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_pulic_info
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personPulicInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_bad_record
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personBadRecord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_remark
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private String personRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person.person_creator_id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	private Integer personCreatorId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.id
	 * @return  the value of person.id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.id
	 * @param id  the value for person.id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_name
	 * @return  the value of person.person_name
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonName() {
		return personName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_name
	 * @param personName  the value for person.person_name
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonName(String personName) {
		this.personName = personName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_name_en
	 * @return  the value of person.person_name_en
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonNameEn() {
		return personNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_name_en
	 * @param personNameEn  the value for person.person_name_en
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonNameEn(String personNameEn) {
		this.personNameEn = personNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_region
	 * @return  the value of person.person_region
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonRegion() {
		return personRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_region
	 * @param personRegion  the value for person.person_region
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonRegion(String personRegion) {
		this.personRegion = personRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_nation
	 * @return  the value of person.person_nation
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonNation() {
		return personNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_nation
	 * @param personNation  the value for person.person_nation
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonNation(String personNation) {
		this.personNation = personNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_passport
	 * @return  the value of person.person_passport
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonPassport() {
		return personPassport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_passport
	 * @param personPassport  the value for person.person_passport
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonPassport(String personPassport) {
		this.personPassport = personPassport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_idcard
	 * @return  the value of person.person_idcard
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonIdcard() {
		return personIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_idcard
	 * @param personIdcard  the value for person.person_idcard
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonIdcard(String personIdcard) {
		this.personIdcard = personIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_sex
	 * @return  the value of person.person_sex
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonSex() {
		return personSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_sex
	 * @param personSex  the value for person.person_sex
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonSex(String personSex) {
		this.personSex = personSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_birthday
	 * @return  the value of person.person_birthday
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public Date getPersonBirthday() {
		return personBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_birthday
	 * @param personBirthday  the value for person.person_birthday
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonBirthday(Date personBirthday) {
		this.personBirthday = personBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_education_level
	 * @return  the value of person.person_education_level
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonEducationLevel() {
		return personEducationLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_education_level
	 * @param personEducationLevel  the value for person.person_education_level
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonEducationLevel(String personEducationLevel) {
		this.personEducationLevel = personEducationLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_address
	 * @return  the value of person.person_address
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonAddress() {
		return personAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_address
	 * @param personAddress  the value for person.person_address
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonAddress(String personAddress) {
		this.personAddress = personAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_specialty
	 * @return  the value of person.person_specialty
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonSpecialty() {
		return personSpecialty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_specialty
	 * @param personSpecialty  the value for person.person_specialty
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonSpecialty(String personSpecialty) {
		this.personSpecialty = personSpecialty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_work_experience
	 * @return  the value of person.person_work_experience
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonWorkExperience() {
		return personWorkExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_work_experience
	 * @param personWorkExperience  the value for person.person_work_experience
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonWorkExperience(String personWorkExperience) {
		this.personWorkExperience = personWorkExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_pulic_info
	 * @return  the value of person.person_pulic_info
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonPulicInfo() {
		return personPulicInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_pulic_info
	 * @param personPulicInfo  the value for person.person_pulic_info
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonPulicInfo(String personPulicInfo) {
		this.personPulicInfo = personPulicInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_bad_record
	 * @return  the value of person.person_bad_record
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonBadRecord() {
		return personBadRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_bad_record
	 * @param personBadRecord  the value for person.person_bad_record
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonBadRecord(String personBadRecord) {
		this.personBadRecord = personBadRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_remark
	 * @return  the value of person.person_remark
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public String getPersonRemark() {
		return personRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_remark
	 * @param personRemark  the value for person.person_remark
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonRemark(String personRemark) {
		this.personRemark = personRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person.person_creator_id
	 * @return  the value of person.person_creator_id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public Integer getPersonCreatorId() {
		return personCreatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person.person_creator_id
	 * @param personCreatorId  the value for person.person_creator_id
	 * @mbggenerated  Sat Dec 28 15:56:31 CST 2013
	 */
	public void setPersonCreatorId(Integer personCreatorId) {
		this.personCreatorId = personCreatorId;
	}
}