package com.wuseguang.report.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserBaseExample extends BaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public UserBaseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null)
				return;
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null)
				return;
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null)
				return;
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserSexIsNull() {
			addCriterion("user_sex is null");
			return (Criteria) this;
		}

		public Criteria andUserSexIsNotNull() {
			addCriterion("user_sex is not null");
			return (Criteria) this;
		}

		public Criteria andUserSexEqualTo(Integer value) {
			addCriterion("user_sex =", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexNotEqualTo(Integer value) {
			addCriterion("user_sex <>", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexGreaterThan(Integer value) {
			addCriterion("user_sex >", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_sex >=", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexLessThan(Integer value) {
			addCriterion("user_sex <", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexLessThanOrEqualTo(Integer value) {
			addCriterion("user_sex <=", value, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexIn(List<Integer> values) {
			addCriterion("user_sex in", values, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexNotIn(List<Integer> values) {
			addCriterion("user_sex not in", values, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexBetween(Integer value1, Integer value2) {
			addCriterion("user_sex between", value1, value2, "userSex");
			return (Criteria) this;
		}

		public Criteria andUserSexNotBetween(Integer value1, Integer value2) {
			addCriterion("user_sex not between", value1, value2, "userSex");
			return (Criteria) this;
		}

		public Criteria andDepartIdIsNull() {
			addCriterion("depart_id is null");
			return (Criteria) this;
		}

		public Criteria andDepartIdIsNotNull() {
			addCriterion("depart_id is not null");
			return (Criteria) this;
		}

		public Criteria andDepartIdEqualTo(Integer value) {
			addCriterion("depart_id =", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdNotEqualTo(Integer value) {
			addCriterion("depart_id <>", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdGreaterThan(Integer value) {
			addCriterion("depart_id >", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("depart_id >=", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdLessThan(Integer value) {
			addCriterion("depart_id <", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdLessThanOrEqualTo(Integer value) {
			addCriterion("depart_id <=", value, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdIn(List<Integer> values) {
			addCriterion("depart_id in", values, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdNotIn(List<Integer> values) {
			addCriterion("depart_id not in", values, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdBetween(Integer value1, Integer value2) {
			addCriterion("depart_id between", value1, value2, "departId");
			return (Criteria) this;
		}

		public Criteria andDepartIdNotBetween(Integer value1, Integer value2) {
			addCriterion("depart_id not between", value1, value2, "departId");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayIsNull() {
			addCriterion("user_birthday is null");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayIsNotNull() {
			addCriterion("user_birthday is not null");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("user_birthday =", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("user_birthday <>", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("user_birthday >", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("user_birthday >=", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("user_birthday <", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("user_birthday <=", value, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("user_birthday in", values, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("user_birthday not in", values,
					"userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("user_birthday between", value1, value2,
					"userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("user_birthday not between", value1,
					value2, "userBirthday");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNull() {
			addCriterion("user_email is null");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNotNull() {
			addCriterion("user_email is not null");
			return (Criteria) this;
		}

		public Criteria andUserEmailEqualTo(String value) {
			addCriterion("user_email =", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotEqualTo(String value) {
			addCriterion("user_email <>", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThan(String value) {
			addCriterion("user_email >", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
			addCriterion("user_email >=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThan(String value) {
			addCriterion("user_email <", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThanOrEqualTo(String value) {
			addCriterion("user_email <=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLike(String value) {
			addCriterion("user_email like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotLike(String value) {
			addCriterion("user_email not like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailIn(List<String> values) {
			addCriterion("user_email in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotIn(List<String> values) {
			addCriterion("user_email not in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailBetween(String value1, String value2) {
			addCriterion("user_email between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotBetween(String value1, String value2) {
			addCriterion("user_email not between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIsNull() {
			addCriterion("user_idcard is null");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIsNotNull() {
			addCriterion("user_idcard is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdcardEqualTo(String value) {
			addCriterion("user_idcard =", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotEqualTo(String value) {
			addCriterion("user_idcard <>", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardGreaterThan(String value) {
			addCriterion("user_idcard >", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardGreaterThanOrEqualTo(String value) {
			addCriterion("user_idcard >=", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLessThan(String value) {
			addCriterion("user_idcard <", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLessThanOrEqualTo(String value) {
			addCriterion("user_idcard <=", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLike(String value) {
			addCriterion("user_idcard like", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotLike(String value) {
			addCriterion("user_idcard not like", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIn(List<String> values) {
			addCriterion("user_idcard in", values, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotIn(List<String> values) {
			addCriterion("user_idcard not in", values, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardBetween(String value1, String value2) {
			addCriterion("user_idcard between", value1, value2, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotBetween(String value1, String value2) {
			addCriterion("user_idcard not between", value1, value2,
					"userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserCodeIsNull() {
			addCriterion("user_code is null");
			return (Criteria) this;
		}

		public Criteria andUserCodeIsNotNull() {
			addCriterion("user_code is not null");
			return (Criteria) this;
		}

		public Criteria andUserCodeEqualTo(String value) {
			addCriterion("user_code =", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeNotEqualTo(String value) {
			addCriterion("user_code <>", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeGreaterThan(String value) {
			addCriterion("user_code >", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
			addCriterion("user_code >=", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeLessThan(String value) {
			addCriterion("user_code <", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeLessThanOrEqualTo(String value) {
			addCriterion("user_code <=", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeLike(String value) {
			addCriterion("user_code like", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeNotLike(String value) {
			addCriterion("user_code not like", value, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeIn(List<String> values) {
			addCriterion("user_code in", values, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeNotIn(List<String> values) {
			addCriterion("user_code not in", values, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeBetween(String value1, String value2) {
			addCriterion("user_code between", value1, value2, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserCodeNotBetween(String value1, String value2) {
			addCriterion("user_code not between", value1, value2, "userCode");
			return (Criteria) this;
		}

		public Criteria andUserPasswordIsNull() {
			addCriterion("user_password is null");
			return (Criteria) this;
		}

		public Criteria andUserPasswordIsNotNull() {
			addCriterion("user_password is not null");
			return (Criteria) this;
		}

		public Criteria andUserPasswordEqualTo(String value) {
			addCriterion("user_password =", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordNotEqualTo(String value) {
			addCriterion("user_password <>", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordGreaterThan(String value) {
			addCriterion("user_password >", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("user_password >=", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordLessThan(String value) {
			addCriterion("user_password <", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordLessThanOrEqualTo(String value) {
			addCriterion("user_password <=", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordLike(String value) {
			addCriterion("user_password like", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordNotLike(String value) {
			addCriterion("user_password not like", value, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordIn(List<String> values) {
			addCriterion("user_password in", values, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordNotIn(List<String> values) {
			addCriterion("user_password not in", values, "userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordBetween(String value1, String value2) {
			addCriterion("user_password between", value1, value2,
					"userPassword");
			return (Criteria) this;
		}

		public Criteria andUserPasswordNotBetween(String value1, String value2) {
			addCriterion("user_password not between", value1, value2,
					"userPassword");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneIsNull() {
			addCriterion("user_telphone is null");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneIsNotNull() {
			addCriterion("user_telphone is not null");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneEqualTo(String value) {
			addCriterion("user_telphone =", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneNotEqualTo(String value) {
			addCriterion("user_telphone <>", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneGreaterThan(String value) {
			addCriterion("user_telphone >", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneGreaterThanOrEqualTo(String value) {
			addCriterion("user_telphone >=", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneLessThan(String value) {
			addCriterion("user_telphone <", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneLessThanOrEqualTo(String value) {
			addCriterion("user_telphone <=", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneLike(String value) {
			addCriterion("user_telphone like", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneNotLike(String value) {
			addCriterion("user_telphone not like", value, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneIn(List<String> values) {
			addCriterion("user_telphone in", values, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneNotIn(List<String> values) {
			addCriterion("user_telphone not in", values, "userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneBetween(String value1, String value2) {
			addCriterion("user_telphone between", value1, value2,
					"userTelphone");
			return (Criteria) this;
		}

		public Criteria andUserTelphoneNotBetween(String value1, String value2) {
			addCriterion("user_telphone not between", value1, value2,
					"userTelphone");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_base
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 22 14:01:50 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}