package com.wuseguang.report.db.pojo;

import java.util.Date;

public class UserBase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_name
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_sex
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private Integer userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.depart_id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private Integer departId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_birthday
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private Date userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_email
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_idcard
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userIdcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_code
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_password
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_base.user_telphone
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	private String userTelphone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.id
	 * @return  the value of user_base.id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.id
	 * @param id  the value for user_base.id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_name
	 * @return  the value of user_base.user_name
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_name
	 * @param userName  the value for user_base.user_name
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_sex
	 * @return  the value of user_base.user_sex
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Integer getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_sex
	 * @param userSex  the value for user_base.user_sex
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserSex(Integer userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.depart_id
	 * @return  the value of user_base.depart_id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Integer getDepartId() {
		return departId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.depart_id
	 * @param departId  the value for user_base.depart_id
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setDepartId(Integer departId) {
		this.departId = departId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_birthday
	 * @return  the value of user_base.user_birthday
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public Date getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_birthday
	 * @param userBirthday  the value for user_base.user_birthday
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_email
	 * @return  the value of user_base.user_email
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_email
	 * @param userEmail  the value for user_base.user_email
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_idcard
	 * @return  the value of user_base.user_idcard
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserIdcard() {
		return userIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_idcard
	 * @param userIdcard  the value for user_base.user_idcard
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserIdcard(String userIdcard) {
		this.userIdcard = userIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_code
	 * @return  the value of user_base.user_code
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_code
	 * @param userCode  the value for user_base.user_code
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_password
	 * @return  the value of user_base.user_password
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_password
	 * @param userPassword  the value for user_base.user_password
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_base.user_telphone
	 * @return  the value of user_base.user_telphone
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public String getUserTelphone() {
		return userTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_base.user_telphone
	 * @param userTelphone  the value for user_base.user_telphone
	 * @mbggenerated  Thu Dec 26 19:35:02 CST 2013
	 */
	public void setUserTelphone(String userTelphone) {
		this.userTelphone = userTelphone;
	}
}